<?php

namespace FrontOfficeBundle\Repository;

/**
 * HouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseRepository extends \Doctrine\ORM\EntityRepository
{
	public function getHousesByProjectId($id)
	{
		$queryB=$this->createQueryBuilder('a');
		$queryB      ->select('h')
		             ->from('FrontOfficeBundle:House', 'h')
		             ->where('h.project = :id')
		             ->andWhere('h.shop = 1')
		             ->setParameter('id', $id);
		return $queryB;
	}

	public function getShopsByProjectId($id)
	{
		$queryB=$this->createQueryBuilder('a');
		$queryB      ->select('h')
		             ->from('FrontOfficeBundle:House', 'h')
		             ->where('h.project = :id')
		             ->andWhere('h.shop = 2')
		             ->setParameter('id', $id);
		return $queryB;
	}
}
