<?php

namespace FrontOfficeBundle\Repository;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPartnerByProject($id)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT p 
			FROM FrontOfficeBundle:Partner p
			JOIN p.project po
			WHERE p.active = 1 
			AND po.id = :idProject')
		->setParameter('idProject', $id);

		return $query->getResult();
	}
}
