<?php

namespace FrontOfficeBundle\Repository;

/**
 * PlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlotRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPlotsByProjectId($id)
	{
		$queryB=$this->createQueryBuilder('a');
		$queryB      ->select('p')
		             ->from('FrontOfficeBundle:Plot', 'p')
		             ->where('p.project = :id')
		             ->setParameter('id', $id);
		return $queryB;
	}
}
