<?php

namespace FrontOfficeBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
	public function getProjectActive()
	{
		$qb=$this->createQueryBuilder('p');
		$qb->where('p.active = 1')
		   ->orderby('p.name','ASC') ;

		return $qb;
	}

	public function getShopsByProject($idProject)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT s 
			FROM FrontOfficeBundle House h
			JOIN h.project p
			WHERE h.shop = 2
			AND p.id LIKE :idProject')
		->setParameter('idProject', $idProject);

		return $query->getResult();
	}

	public function getHousesByProject($idProject)
	{
		$query=$this->getEntityManager()->createQuery('
			SELECT s 
			FROM FrontOfficeBundle House h
			JOIN h.project p
			WHERE h.shop = 1
			AND p.id LIKE :idProject')
		->setParameter('idProject', $idProject);

		return $query->getResult();
	}
}
